name: minerl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - py-opencv
  - cudatoolkit=10.2
  - pip:
    - git+https://github.com/minerllabs/minerl
    - coloredlogs
    - matplotlib
    - aicrowd-api
    - aicrowd-gym

